import { RootObject } from '../Data/cta_dto';

export const sampleData: RootObject = {
  ctatt: {
    tmst: new Date(),
    errCd: '0',
    errNm: null,
    eta: [
      {
        staId: '40360',
        stpId: '30070',
        staNm: 'Southport',
        stpDe: 'Service toward Kimball',
        rn: '426',
        rt: 'Brn',
        destSt: '30249',
        destNm: 'Kimball',
        trDr: '1',
        prdt: new Date(),
        arrT: new Date(),
        isApp: '0',
        isSch: '0',
        isDly: '0',
        isFlt: '0',
        flags: null,
        lat: '41.93276',
        lon: '-87.65313',
        heading: '359'
      },
      {
        staId: '40360',
        stpId: '30071',
        staNm: 'Southport',
        stpDe: 'Service toward Loop',
        rn: '422',
        rt: 'Brn',
        destSt: '30249',
        destNm: 'Loop',
        trDr: '5',
        prdt: new Date(),
        arrT: new Date(),
        isApp: '0',
        isSch: '0',
        isDly: '0',
        isFlt: '0',
        flags: null,
        lat: '41.96175',
        lon: '-87.67517',
        heading: '179'
      },
      {
        staId: '40360',
        stpId: '30071',
        staNm: 'Southport',
        stpDe: 'Service toward Loop',
        rn: '423',
        rt: 'Brn',
        destSt: '30249',
        destNm: 'Loop',
        trDr: '5',
        prdt: new Date(),
        arrT: new Date(),
        isApp: '0',
        isSch: '0',
        isDly: '0',
        isFlt: '0',
        flags: null,
        lat: '41.96609',
        lon: '-87.70882',
        heading: '89'
      },
      {
        staId: '40360',
        stpId: '30070',
        staNm: 'Southport',
        stpDe: 'Service toward Kimball',
        rn: '433',
        rt: 'Brn',
        destSt: '30249',
        destNm: 'Kimball',
        trDr: '1',
        prdt: new Date(),
        arrT: new Date(),
        isApp: '0',
        isSch: '0',
        isDly: '0',
        isFlt: '0',
        flags: null,
        lat: '41.91041',
        lon: '-87.63886',
        heading: '269'
      }
    ]
  }
};
